baseURL = '/'
defaultContentLanguage = 'pt-br'
title = 'Doenças Crônicas não Transmissíveis'
summary = 'Curso Doenças Crônicas não Transmissíveis (DCNT) e o Desafio da Vigilância em Saúde nas Regiões Fronteiriças'
relativeURLs = true
removePathAccents = true
pluralizeListTitles = false
enableRobotsTXT = true
disableHugoGeneratorInject = true
disableKinds = ['taxonomy']
mainSections = ['luana', 'thiago', 'mariana', 'pedro']
[params]
  subtitle = 'e o Desafio da Vigilância em Saúde nas Regiões Fronteiriças'
  [params.meta]
    msColor = '#ffffff'
[module]
  [[module.mounts]]
    disableWatch = false
    lang = ''
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = "node_modules/bootstrap/scss"
    target = "assets/recursos/css/bootstrap/source"
  [[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-free/svgs"
    target = "assets/recursos/svg"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.esm.min.js"
    target = "assets/recursos/js/bootstrap/bootstrap.min.mjs"
  [[module.mounts]]
    source = "node_modules/@popperjs/core/dist/esm"
    target = "assets/recursos/js/popperjs/core/dist/esm"
  [[module.mounts]]
    source = "node_modules/panzoom/dist/panzoom.min.js"
    target = "assets/recursos/js/panzoom/panzoom.min.js"
[services]
  [services.googleAnalytics]
    id = 'G-WXPN4ETG2Q'
