baseURL = '/'
defaultContentLanguage = 'pt-br'
title = 'Lorem ipsum laboris'
summary = 'Curso Doenças Crônicas não Transmissíveis(DCNT) e o Desafio da Vigilância em Saúde nas Regiões Fronteiriças'
relativeURLs = true
pluralizeListTitles = false
enableRobotsTXT = true
disableHugoGeneratorInject = true
[params.meta]
  msColor = "#ffffff"
[menus]
  [[menus.main]]
    name = 'Módulos'
    weight = 10
  [[menus.main]]
    name = 'Bibliografia'
    weight = 90
  [[menus.main]]
    name = 'Créditos'
    weight = 90
[module]
  [[module.mounts]]
    disableWatch = false
    lang = ''
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-free/svgs"
    target = "assets/svg"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.esm.min.js"
    target = "assets/js/bootstrap/bootstrap.min.mjs"
  [[module.mounts]]
    source = "node_modules/@popperjs"
    target = "assets/js/popperjs"
[services]
  [services.googleAnalytics]
    id = 'G-MEASUREMENT_ID'